"""User domain models, roles, and API key generation and hashing.
"""

from __future__ import annotations

import hashlib
import secrets
from enum import StrEnum

__all__ = [
    "API_KEY_PREFIX",
    "Role",
    "generate_api_key",
    "hash_api_key",
]

#: Standard prefix for UAP API keys for recognition and secret scanning.
API_KEY_PREFIX = "uap_"


class Role(StrEnum):
    """User authorization roles."""

    ADMIN = "admin"
    MEMBER = "member"
    VIEWER = "viewer"


def generate_api_key() -> str:
    """Generate a high-entropy, cryptographically random API key.

    Uses ``secrets.token_urlsafe(32)``, providing 256 bits of cryptographic entropy.
    Prefixed with ``uap_`` for ease of credential scanning, secret detection,
    and routing.
    """
    return f"{API_KEY_PREFIX}{secrets.token_urlsafe(32)}"


def hash_api_key(key: str) -> str:
    """Hash an API key using SHA-256 for persistent storage.

    Why hashlib.sha256 instead of bcrypt/argon2:
    API keys generated by `generate_api_key()` have 256 bits of cryptographic
    entropy. Unlike low-entropy human passwords, brute-force dictionary attacks
    and rainbow tables are computationally impossible against 256-bit keys.
    Key-derivation functions (KDFs) like bcrypt or argon2 are intentionally CPU-
    and memory-heavy to slow down password cracking; running them on every API
    request would introduce significant latency and expose the server to denial-
    of-service attacks. In contrast, SHA-256 offers pre-image resistance and
    fast, constant-time database indexing with zero DoS vulnerability.
    """
    # ponytail: SHA-256 raw hex without per-key salt; upgrade to HMAC-SHA256 if DB leak model expands to cross-tenant DB dumps.
    return hashlib.sha256(key.encode("utf-8")).hexdigest()
